version: '3.9'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5101:80"
      - "5341:5341"
    volumes:
      - ./.docker-data/seq:/data
